defaults: &defaults  
    host: <%= ENV['MONGOID_HOST'] %>
    port: <%= ENV['MONGOID_PORT'] %>
    username: <%= ENV['MONGOID_USER'] %>
    password: <%= ENV['MONGOID_PASS'] %>
    database: <%= ENV['MONGOID_DATABASE'] %>

development:
  sessions:
    default:
      hosts:
        - localhost:27017
      database: poker

test:  
    <<: *defaults
        
production:  
    <<: *defaults